---
- name: Root password reset.
  hosts: all
  vars_files:
    - root_password_file.yaml 
  tasks:
    - name: Update the root paassword.
      ansible.builtin.user:
        name: root 
        password: "{{ new_root_pass | password_hash('sha512')}}"
        #password: "{{ new_root_pass | password_hash('sha256')}}"
        #password: "{{ 'cp' | password_hash('sha512')}}"
