---
- name: Conditonal statement example.
  hosts: servera.lab.example.com 
  tasks:
    - name: task-01 with condition 
      ansible.builtin.debug:
        msg: "This is 1st task \n"
      when: true 
    - name: task-02 with condition 
      ansible.builtin.debug:
        msg: "This is 2nd task \n"
      when: false
