---
- name: Some condition example.
  hosts: all
  vars:
     var1: data
  tasks:
    - name: Task-01 - just display
      ansible.builtin.debug:
        msg: "This is 1st task \n"
      #when: var1 is defined 
      when: var1 is not defined 
