---
- name: Loop example, passing list of dictionary
  hosts: all
  tasks:
    - name: Passing List only
      ansible.builtin.group:
        name: "{{ item }}"
        state: present 
      loop: 
         - unixadm 
         - dbadm 
    - name: Passing List of dictionary 
      ansible.builtin.user:
        name: "{{ item.username}}"
        uid: "{{ item.uid_no }}"
        group: "{{ item.group }}"
        state: present
      loop:
         - {username: user1 , uid_no: 12345 , group: unixadm}
         - {username: user2 , uid_no: 54321 , group: dbadm}
         - username: user3 
           uid_no: 65432
           group: unixadm
