---
- name: Loop example for list.
  hosts: servera.lab.example.com 
  vars_files:
   - multiple_svc_list.yaml
  tasks:
    - name: Restart multiple services.
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted 
      loop: "{{ service_list }}"

