---
- name: Use ansible facts.
  hosts: servera.lab.example.com
  tasks:
    - name: System info via ansible facts.
      ansible.builtin.debug:
        msg: >
           IP-Address= {{  ansible_facts['default_ipv4']['address'] }} 
           Mac-Address= {{ ansible_facts['default_ipv4']['macaddress']}}
    - name: Collect only hardware facts
      ansible.builtin.setup:
        gather_subset:
        - hardware
      register: outcome 

    - name: OutCome display
      ansible.builtin.debug:
        var: outcome
