---
- name: Error handling example
  hosts: servera.lab.example.com
  tasks:
    - name: task01
      ansible.builtin.debug: 
        msg: "This is task-01"
      register: output_task01 

    - name: Display
      ansible.builtin.debug:
        var: output_task01
      failed_when: true       
      ignore_errors: true

    - name: task02
      ansible.builtin.debug: 
        msg: "This is task-03"
      when: output_task01.failed == true 

    - name: task04-Example using fail and when together
      ansible.builtin.fail:
        msg: The system may not be provisioned according to the CMDB status.
      when: output_task01.failed == false 
